-- EXIBE TODOS OS REGISTROS DA TABELA CUSTOMERS
SELECT
	*
FROM
	CUSTOMERS;
-- EXIBE O NOME DE CONTATO E A CIDADE DOS CLIENTES
SELECT
	CONTACT_NAME,
	CITY
FROM
	CUSTOMERS;
-- LISTA TODOS OS PAÍSES DOS CLIENTES
SELECT
	COUNTRY
FROM
	CUSTOMERS;
-- LISTA OS PAÍSES SEM REPETIÇÃO
SELECT
	DISTINCT COUNTRY
FROM
	CUSTOMERS;
-- CONTA QUANTOS PAÍSES ÚNICOS EXISTEM
SELECT
	COUNT(DISTINCT COUNTRY)
FROM
	CUSTOMERS;
-- SELECIONA TODOS OS CLIENTES DO MÉXICO
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY = 'MEXICO';
-- SELECIONA CLIENTES COM ID ESPECÍFICO
SELECT
	*
FROM
	CUSTOMERS
WHERE
	CUSTOMER_ID = 'ANATR';
-- UTILIZA AND PARA MÚLTIPLOS CRITÉRIOS
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY = 'GERMANY'
	AND CITY = 'BERLIN';
-- UTILIZA OR PARA MAIS DE UMA CIDADE
SELECT
	*
FROM
	CUSTOMERS
WHERE
	CITY = 'BERLIN'
	OR CITY = 'AACHEN';
-- UTILIZA NOT PARA EXCLUIR A ALEMANHA
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY <> 'GERMANY';
-- COMBINA AND, OR E NOT
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY = 'GERMANY'
	AND (
		CITY = 'BERLIN'
			OR CITY = 'AACHEN'
	);
-- EXCLUI CLIENTES DA ALEMANHA E EUA
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY <> 'GERMANY'
	AND COUNTRY <> 'USA';
-- CLIENTES COM NOME DE CONTATO COMEÇANDO POR "A"
SELECT
	*
FROM
	CUSTOMERS
WHERE
	CONTACT_NAME LIKE 'A%';
-- CLIENTES COM NOME DE CONTATO NÃO COMEÇANDO POR "A"
SELECT
	*
FROM
	CUSTOMERS
WHERE
	CONTACT_NAME NOT LIKE 'A%';
-- CLIENTES DE PAÍSES ESPECÍFICOS
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY IN (
		'GERMANY', 'FRANCE', 'UK'
	);
-- CLIENTES NÃO LOCALIZADOS EM 'GERMANY', 'FRANCE', 'UK'
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY NOT IN (
		'GERMANY', 'FRANCE', 'UK'
	);