/*################################################################################################
############################################ DESAFIO #############################################
################################################################################################*/

-- 1. OBTER TODAS AS COLUNAS DAS TABELAS CLIENTES, PEDIDOS E FORNECEDORES

SELECT
*
FROM
CUSTOMERS C ;

SELECT
*
FROM
ORDERS O ;

SELECT
*
FROM
SUPPLIERS S ;

-- 2. OBTER TODOS OS CLIENTES EM ORDEM ALFABÉTICA POR PAÍS E NOME

SELECT
*
FROM
CUSTOMERS C
ORDER BY
COUNTRY,
COMPANY_NAME ;

-- 3. OBTER OS 5 PEDIDOS MAIS ANTIGOS

SELECT
*
FROM
ORDERS O
ORDER BY
ORDER_DATE
LIMIT 5


-- 4. OBTER A CONTAGEM DE TODOS OS PEDIDOS FEITOS DURANTE 1997

SELECT
COUNT(*) QUANTITY
FROM
ORDERS O
WHERE
EXTRACT(YEAR
FROM
ORDER_DATE) = 1997;

-- 5. OBTER OS NOMES DE TODAS AS PESSOAS DE CONTATO ONDE A PESSOA É UM GERENTE, EM ORDEM ALFABÉTICA

SELECT
*
FROM
SUPPLIERS
WHERE
UPPER(CONTACT_TITLE) LIKE '%MANAGER%'
ORDER BY
CONTACT_NAME ;

-- 6. OBTER TODOS OS PEDIDOS FEITOS EM 19 DE MAIO DE 1997

SELECT
*
FROM
ORDERS
WHERE
ORDER_DATE = '1997-05-19';
