-- 1. CRIA UM RELATÓRIO PARA TODOS OS PEDIDOS DE 1996 E SEUS CLIENTES (152 LINHAS)

SELECT
*
FROM
ORDERS A
INNER JOIN CUSTOMERS B ON
A.CUSTOMER_ID = B.CUSTOMER_ID
WHERE
EXTRACT(YEAR
FROM
ORDER_DATE) = 1996;


-- 2. CRIA UM RELATÓRIO QUE MOSTRA O NÚMERO DE FUNCIONÁRIOS E CLIENTES DE CADA CIDADE QUE TEM FUNCIONÁRIOS (5 LINHAS)

SELECT
	E.CITY AS CIDADE,
	COUNT(DISTINCT E.EMPLOYEE_ID) AS NUMERO_DE_FUNCIONARIOS,
	COUNT(DISTINCT C.CUSTOMER_ID) AS NUMERO_DE_CLIENTES
FROM
	EMPLOYEES E
LEFT JOIN CUSTOMERS C ON
	E.CITY = C.CITY
GROUP BY
	E.CITY
ORDER BY
	CIDADE;

-- 3. CRIA UM RELATÓRIO QUE MOSTRA O NÚMERO DE FUNCIONÁRIOS E CLIENTES DE CADA CIDADE QUE TEM CLIENTES (69 LINHAS)

SELECT
C.CITY AS CIDADE,
COUNT(DISTINCT C.CUSTOMER_ID) AS NUMERO_DE_CLIENTES,
COUNT(DISTINCT E.EMPLOYEE_ID) AS NUMERO_DE_FUNCIONARIOS
FROM
EMPLOYEES E
RIGHT JOIN CUSTOMERS C ON
E.CITY = C.CITY
GROUP BY
C.CITY
ORDER BY
CIDADE;

-- 4.CRIA UM RELATÓRIO QUE MOSTRA O NÚMERO DE FUNCIONÁRIOS E CLIENTES DE CADA CIDADE (71 LINHAS)

SELECT
COALESCE(E.CITY,
C.CITY) AS CIDADE,
COUNT(DISTINCT E.EMPLOYEE_ID) AS NUMERO_DE_FUNCIONARIOS,
COUNT(DISTINCT C.CUSTOMER_ID) AS NUMERO_DE_CLIENTES
FROM
EMPLOYEES E
FULL JOIN CUSTOMERS C ON
E.CITY = C.CITY
GROUP BY
E.CITY,
C.CITY
ORDER BY
CIDADE;


-- 5. CRIA UM RELATÓRIO QUE MOSTRA A QUANTIDADE TOTAL DE PRODUTOS ENCOMENDADOS.
-- MOSTRA APENAS REGISTROS PARA PRODUTOS PARA OS QUAIS A QUANTIDADE ENCOMENDADA É MENOR QUE 200 (5 LINHAS)

SELECT
O.PRODUCT_ID,
P.PRODUCT_NAME,
SUM(O.QUANTITY) AS QUANTIDADE_TOTAL
FROM
ORDER_DETAILS O
JOIN PRODUCTS P ON
P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
O.PRODUCT_ID,
P.PRODUCT_NAME
HAVING
SUM(O.QUANTITY) < 200
ORDER BY
QUANTIDADE_TOTAL DESC

-- 6. CRIA UM RELATÓRIO QUE MOSTRA O TOTAL DE PEDIDOS POR CLIENTE DESDE 31 DE DEZEMBRO DE 1996.
-- O RELATÓRIO DEVE RETORNAR APENAS LINHAS PARA AS QUAIS O TOTAL DE PEDIDOS É MAIOR QUE 15 (5 LINHAS)

SELECT
CUSTOMER_ID,
COUNT(ORDER_ID) AS TOTAL_DE_PEDIDOS
FROM
ORDERS
WHERE
ORDER_DATE > '1996-12-31'
GROUP BY
CUSTOMER_ID
HAVING
COUNT(ORDER_ID) > 15
ORDER BY
TOTAL_DE_PEDIDOS;