DROP VIEW TOTAL_REVENUES_1997_VIEW;

CREATE VIEW TOTAL_REVENUES_1997_VIEW AS
SELECT SUM((ORDER_DETAILS.UNIT_PRICE) * ORDER_DETAILS.QUANTITY * (1.0 - ORDER_DETAILS.DISCOUNT)) AS TOTAL_REVENUES_1997
FROM ORDER_DETAILS
INNER JOIN (
SELECT ORDER_ID
FROM ORDERS
WHERE EXTRACT(YEAR
FROM ORDER_DATE) = '1997'
) AS ORD
ON
ORD.ORDER_ID = ORDER_DETAILS.ORDER_ID;

SELECT *
FROM TOTAL_REVENUES_1997_VIEW;