DROP VIEW VIEW_RECEITAS_ACUMULADAS;

CREATE VIEW VIEW_RECEITAS_ACUMULADAS AS
WITH RECEITASMENSAIS AS (
SELECT EXTRACT(YEAR
FROM ORDERS.ORDER_DATE) AS ANO, EXTRACT(MONTH
FROM ORDERS.ORDER_DATE) AS MES, SUM(ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY * (1.0 - ORDER_DETAILS.DISCOUNT)) AS RECEITA_MENSAL
FROM ORDERS
INNER JOIN
ORDER_DETAILS ON
ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
GROUP BY
EXTRACT(YEAR
FROM ORDERS.ORDER_DATE), EXTRACT(MONTH
FROM ORDERS.ORDER_DATE)
), RECEITASACUMULADAS AS (
SELECT ANO, MES, RECEITA_MENSAL, SUM(RECEITA_MENSAL) OVER (PARTITION BY ANO
ORDER BY MES) AS RECEITA_YTD
FROM RECEITASMENSAIS
)
SELECT ANO, MES, RECEITA_MENSAL, RECEITA_MENSAL - LAG(RECEITA_MENSAL) OVER (PARTITION BY ANO
ORDER BY MES) AS DIFERENCA_MENSAL, RECEITA_YTD,(RECEITA_MENSAL - LAG(RECEITA_MENSAL) OVER (PARTITION BY ANO
ORDER BY MES)) / LAG(RECEITA_MENSAL) OVER (PARTITION BY ANO
ORDER BY MES) * 100 AS PERCENTUAL_MUDANCA_MENSAL
FROM RECEITASACUMULADAS
ORDER BY
ANO, MES;

SELECT *
FROM VIEW_RECEITAS_ACUMULADAS;