DROP VIEW CLIENTS_TO_MARKETING;

CREATE VIEW CLIENTS_TO_MARKETING AS
WITH CLIENTES_PARA_MARKETING AS (
SELECT CUSTOMERS.COMPANY_NAME, SUM(ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY * (1.0 - ORDER_DETAILS.DISCOUNT)) AS TOTAL, NTILE(5) OVER (
ORDER BY SUM(ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY * (1.0 - ORDER_DETAILS.DISCOUNT)) DESC) AS GROUP_NUMBER
FROM CUSTOMERS
INNER JOIN
ORDERS ON
CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
INNER JOIN
ORDER_DETAILS ON
ORDER_DETAILS.ORDER_ID = ORDERS.ORDER_ID
GROUP BY
CUSTOMERS.COMPANY_NAME
ORDER BY
TOTAL DESC
)
SELECT *
FROM CLIENTES_PARA_MARKETING
WHERE GROUP_NUMBER >= 3;

SELECT *
FROM CLIENTS_TO_MARKETING;