DROP VIEW UK_CLIENTS_WHO_PAY_MORE_THEN_1000;

CREATE VIEW UK_CLIENTS_WHO_PAY_MORE_THEN_1000 AS
SELECT CUSTOMERS.CONTACT_NAME, SUM(ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY * (1.0 - ORDER_DETAILS.DISCOUNT) * 100) / 100 AS PAYMENTS
FROM CUSTOMERS
INNER JOIN ORDERS ON
ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
INNER JOIN ORDER_DETAILS ON
ORDER_DETAILS.ORDER_ID = ORDERS.ORDER_ID
WHERE LOWER(CUSTOMERS.COUNTRY) = 'UK'
GROUP BY CUSTOMERS.CONTACT_NAME
HAVING SUM(ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY * (1.0 - ORDER_DETAILS.DISCOUNT)) > 1000;

SELECT *
FROM UK_CLIENTS_WHO_PAY_MORE_THEN_1000;